name: Build and Deploy code 


on: [push,pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      -name: pulling get repo 
       uses: actions/checkout@v2

      -name: saying Hi to Hazem
       run: echo "Hi Hazem"